package id.altea.care.view.common.enums

enum class TypeNotification {
    PUSH_NOTIFICATION_APPOINTMENT_PAYMENT_SUCCESS,
    PUSH_NOTIFICATION_APPOINTMENT_REFUNDED,
    PUSH_NOTIFICATION_APPOINTMENT_WAITING_FOR_PAYMENT,
    PUSH_NOTIFICATION_APPOINTMENT_CANCELED_BY_GP,
    PUSH_NOTIFICATION_APPOINTMENT_CANCELED_BY_SYSTEM,
    PUSH_NOTIFICATION_APPOINTMENT_COMPLETED,
    PUSH_NOTIFICATION_APPOINTMENT_MEET_SPECIALIST,
    PUSH_NOTIFICATION_APPOINTMENT_15MINUTES_BEFORE_MEET_SPECIALIST,
    PUSH_NOTIFICATION_APPOINTMENT_10MINUTES_AFTER_ON_GOING,
    PUSH_NOTIFICATION_APPOINTMENT_WILL_ENDED_IN_10MINUTES,
    PUSH_NOTIFICATION_APPOINTMENT_SCHEDULE_CHANGED,
    PUSH_NOTIFICATION_APPOINTMENT_SPECIALIST_CHANGED,
}
