-keep class tvi.webrtc.** { *; }
-keep class com.twilio.video.** { *; }
-keep class com.twilio.common.** { *; }
-keep class com.twilio.audioswitch.** { *; }
-keep class !com.twilio.chat.app.**, com.twilio.chat.** { *; }
-keepattributes InnerClasses
