name: Build & upload to Firebase App Distribution 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - dev
      - pharmacy
      - telemedition

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: build stg 
      run: ./gradlew --stacktrace assembleStgDebug && find -type d -print
    - name: Set output
      id: vars
      run: |
        echo ::set-output name=branch::${GITHUB_REF#refs/*/}
        echo ::set-output name=sha_short::$(git rev-parse --short "$GITHUB_SHA")
    - name: upload apk to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: altea-team
        file: app/build/outputs/apk/stg/debug/app-stg-universal-debug.apk
        releaseNotes: |
          Branch Name       : ${{ steps.vars.outputs.branch }}
          Commit Code       : ${{ steps.vars.outputs.sha_short }}
          Commit Message    : ${{ github.event.head_commit.message }}
          Author            : ${{ github.event.head_commit.author.name }} - ${{ github.event.head_commit.author.email }}
          Times             : ${{ github.event.head_commit.timestamp }}
          Compare           : ${{ github.event.compare }}
